error handling

diff --git a/browser-with-proxy b/browser-with-proxy
--- a/browser-with-proxy
+++ b/browser-with-proxy
@@ -8,7 +8,7 @@ browser="chromium"
 #which country to pull proxies for
 country="uk"
 #test request timeout
-timeout=1
+timeout=2
 #use a (working) proxy at random as opposed to lowest latency first
 random=0
 #we expect to get a 200 response
@@ -23,7 +23,16 @@ fi
 
 if [ "$drystart" = 0 ];then
 
-  list=$(wget -q -O - "https://free-proxy-list.net/${country}-proxy.html"|sed 's/<tr>/\n/g'|grep --color=never '<td>'|awk -F'[<>]' '{print $3":"$7}')
+  rawlist=$(wget -q -O - "https://free-proxy-list.net/${country}-proxy.html")
+  if [ $? -ne 0 ];then
+    echo "failed to retrieve list"
+    exit 1
+  fi
+  list=$(echo "$rawlist"|sed 's/<tr>/\n/g'|grep --color=never '<td>'|awk -F'[<>]' '{print $3":"$7}')
+  if [ -z "$list" ];then
+    echo "failed to parse list"
+    exit 1
+  fi
   
   output=$(
     for host in $list;do
@@ -40,7 +49,11 @@ if [ "$drystart" = 0 ];then
       ) 
     done | sort -n
   )
-  
+  if [ -z "$output" ];then
+    echo "no servers responded properly and in time."
+    exit 1
+  fi
+
   randcmd="head"
   if [ "$random" = "1" ];then
     randcmd="shuff"
@@ -51,6 +64,9 @@ if [ "$drystart" = 0 ];then
     join=""
   fi
   for i in $(seq 1 $limit);do
+    if [ -z "$output" ];then
+      break
+    fi
     http_proxy+=$(echo "$output"|$randcmd -n1|awk '{print "http://"$2":"$3}')"$join"
     output=$(echo "$output"|tail -n +2)
   done
