simplify

diff --git a/quake-scripts/ezquake-clang-profile b/quake-scripts/ezquake-clang-profile
--- a/quake-scripts/ezquake-clang-profile
+++ b/quake-scripts/ezquake-clang-profile
@@ -1,10 +1,16 @@
 #!/bin/bash -e
 
-quaketestscript="quake +timedemo demos/fps4"
+quaketestcommand="+timedemo demos/fps4"
+quakedir="$HOME/games/quake"
 gitdir="/home/git/ezquake-source-official"
 optimizations="-march=native -O3 -pipe"
 clangver="15"
 profiledir="/tmp/ezquakeprofile"
+
+if [ ! -e "$quakedir/id1/pak0.pak" ];then
+	echo "pak files not found in quakedir.  bailing out."
+	exit 1
+fi
 
 sudo apt -y install clang-$clangver llvm-$clangver lld-$clangver
 
@@ -25,7 +31,7 @@ LDFLAGS=$optimizations -flto -fuse-ld=lld-$clangver -fprofile-use=$profiledir/de
 make clean
 EZ_CONFIG_FILE="$profiledir/.config_1" make -j$(nproc)
 
-$quaketestscript
+./ezquake-linux-$(uname -m) -basedir $quakedir $quaketestcommand
 
 make clean
 
